services:
  pixelated_pipeline:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: pixelated_pipeline
    restart: always
    volumes:
      - "./:/app" # In production comment this
    ports:
      - "8080:8080"