services:
  pixelated_pipeline:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: pixelated_pipeline
    restart: always
    volumes:
      - "./application.yml:/etc/secrets/application.yml" # Maybe comment this on production too
    ports:
      - "8080:8080"