services:
  postgresql_database:
    image: postgres:16.2-alpine3.19
    container_name: postgresql_database
    restart: always
    environment:
      POSTGRES_DB: pixelated-project
      POSTGRES_PASSWORD: change-me-in-prod
      POSTGRES_USER: developer
    networks:
      - database_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pixelated_pipeline:
    build: .
    container_name: pixelated_pipeline
    restart: always
    networks:
      - proxy_network
      - database_network
    depends_on:
      - postgresql_database

  adminer:
    image: adminer
    container_name: adminer_database_ui
    restart: always
    networks:
      - database_network
    depends_on:
      - postgresql_database
    ports:
      - '9000:8080'

  pixelated_pen:
    # TODO: add hmr support https://stackoverflow.com/questions/71297042/react-hot-reload-doesnt-work-in-docker-container
    build: ./web/
    container_name: pixelated_pen
    restart: always
    networks:
      - proxy_network
    depends_on:
      - pixelated_pipeline

  nginx:
    image: nginx:1.25.5-alpine
    restart: always
    container_name: reverse_proxy
    ports:
      # port mappings do not work with host network driver
      - '8008:80'
    extra_hosts:
      # https://stackoverflow.com/questions/27810076/how-do-i-access-a-server-on-localhost-with-nginx-docker-container
      - "dockerhost:192.168.0.115"
    networks:
      - proxy_network
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - pixelated_pipeline
      - pixelated_pen

volumes:
  postgres_volume:
    name: pixelated-project-data
    driver: local

networks:
  proxy_network:
    # https://docs.docker.com/network/drivers/host/ 
    # https://stackoverflow.com/questions/56582446/how-to-use-host-network-for-docker-compose
    # host driver is only available on linux and on docker desktop beta, so not working on windows
    # driver: host
    driver: bridge

  database_network:
    driver: bridge
