services:
  postgresql_database:
    container_name: 'postgresql_database'
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: pixelated-project
      POSTGRES_PASSWORD: change-me-in-prod
      POSTGRES_USER: developer
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '6969:8080'

volumes:
  postgres_volume:
    name: pixelated-project-data
    driver: local
